language: elixir

elixir:
  - 1.3

otp_release:
  - 18.2.1

env:
  global:
    - MIX_ENV=test
    # COVERALLS_REPO_TOKEN
    - secure: "O3qMKMBbTTPUtTo0U9mp0y8EOLwMQ/agHTVZrEuh1WXUDwGsc5GCmlD2MhFdp0XqSZciMEpvmBSmx1sJnOAm6k6X2+ANFY0qtS1x8gfC2U1wJN5hSCe9k4bkSDOht/CxCqTEnitTadefwUnWF9dq0CeA76Hf/DS/xv9yXErVUkzHmmMi1wOrJAUTEVmPsxB8oVxPLCNEfY9ZKShMCDzRYIRiMOd77PXWBQwuhQGMMQ/241YNNCdihqWHb0zN5JmWNKLjGwCLQK6HhFrFeMWogVQa5jJK2pHJTPsRrbWiRqycIvC5X+E5AmsbDBV0nNBPO6j5vW6DMRsi3zH6Y5CEc+/1nqMOHoSQSdSaf133KgIzSW3i6thLDvro77GNksht27rOLULer1e3zxUMtS0TUEkgEKZX6awJZBet2okWIRCZ+L8gu1+rUNuFNSM/fWuiFDY927S3Z9KyHboKgBp8wRmqR5+I3J0rTZTHTth3pDHZB17LAWOBJ8lddv4SzJdK9+T9Hi/wp3b9xluQ59NXO8nVpepilYSChdKAKHyZtAprXAX+7Ulbyj/nuMDykU1jkZ6EHhDWE6Plze0Rj27rlAgje3avXiKnLYldELMbDZwzNFconG+631XqT9i1MgAf4gr5a8/6Cl/ISFYvGwoB9u8n0SaJxUSK3mAqTSIeW/c="

script: mix coveralls.travis
